version: '2.3'

services:
    tvm-dev-fix:
        image: tvm-dev-fix:DietCode
        build:
            context: ./dockerfiles
            dockerfile: tvm.Dockerfile
        runtime: nvidia
        volumes:
            - .:/mnt
        working_dir: /mnt
        privileged: true
