version: '2.3'

services:
    DietCode:
        image: DietCode:stable
        build:
            context: ./dockerfiles
            dockerfile: tvm.Dockerfile
        runtime: nvidia
        volumes:
            - .:/mnt
        working_dir: /mnt
        privileged: true
