name: build

on:
    schedule:
        - cron: "0 9 * * *"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: DietCode (build)
              run: docker-compose run --rm DietCode bash -c "/mnt/ci/1-build.sh tvm"
            - name: Base (Build)
              run: docker-compose run --rm DietCode bash -c "/mnt/ci/1-build.sh tvm_base"
