name: eco-cluster status check

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    runs-on: eco-cluster
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: DietCode (build)
        run: docker-compose run --rm -e NVIDIA_VISIBLE_DEVICES=3 tvm-dev bash -c "/mnt/scripts/1-build.sh tvm"
      - name: Base (Build)
        run: docker-compose run --rm -e NVIDIA_VISIBLE_DEVICES=3 tvm-dev bash -c "/mnt/scripts/1-build.sh tvm_base"
      - name: Code Generation Tests
        run: docker-compose run --rm -e NVIDIA_VISIBLE_DEVICES=3 tvm-dev bash -c "source environ/activate_dietcode.sh && pytest -s tests/codegen"
