name: website

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
              with:
                persist-credentials: false
            - name: Build
              run: cd docs && make html
            - name: Publish
              uses: JamesIves/github-pages-deploy-action@v4.2.3
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: docs/build/html
